"""Add es_responsable_iva and Expense

Revision ID: 112b99a44932
Revises: 5691ac27ba8f
Create Date: 2026-04-01 10:56:04.289951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112b99a44932'
down_revision = '5691ac27ba8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_responsable_iva', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('es_responsable_iva')

    # ### end Alembic commands ###
