"""add_date_indexes

Revision ID: 6db52c9c13fd
Revises: 8508d9bc0410
Create Date: 2026-01-07 02:45:43.964649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db52c9c13fd'
down_revision = '8508d9bc0410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrative_expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrative_expense_fecha'), ['fecha'], unique=False)

    with op.batch_alter_table('contract_installment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_installment_fecha_vencimiento'), ['fecha_vencimiento'], unique=False)

    with op.batch_alter_table('payment_diagnosis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_diagnosis_fecha_pago'), ['fecha_pago'], unique=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_fecha_venta'), ['fecha_venta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_fecha_venta'))

    with op.batch_alter_table('payment_diagnosis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_diagnosis_fecha_pago'))

    with op.batch_alter_table('contract_installment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_installment_fecha_vencimiento'))

    with op.batch_alter_table('administrative_expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrative_expense_fecha'))

    # ### end Alembic commands ###
