"""Add indexes fixed

Revision ID: 8508d9bc0410
Revises: 2cf0f5a4a660
Create Date: 2026-01-07 01:57:43.654702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8508d9bc0410'
down_revision = '2cf0f5a4a660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('client_contract_number_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_client_contract_number'), ['contract_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_numero_id'), ['numero_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_numero_id'))
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.drop_index(batch_op.f('ix_client_contract_number'))
        batch_op.create_unique_constraint(batch_op.f('client_contract_number_key'), ['contract_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
