"""Add Negotiation model and negociador_id to Client

Revision ID: bd5ce4587f22
Revises: 112b99a44932
Create Date: 2026-04-29 15:53:24.562415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5ce4587f22'
down_revision = '112b99a44932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('negociador_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('valor_negociado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['negociador_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['financial_obligation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negociador_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['negociador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('negociador_id')

    op.drop_table('negotiation')
    # ### end Alembic commands ###
