"""Add client acceptance fields to Negotiation

Revision ID: ef6786e6889d
Revises: bd5ce4587f22
Create Date: 2026-04-29 16:04:52.829202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6786e6889d'
down_revision = 'bd5ce4587f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negotiation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aceptada_por_cliente', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_respuesta_cliente', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negotiation', schema=None) as batch_op:
        batch_op.drop_column('fecha_respuesta_cliente')
        batch_op.drop_column('aceptada_por_cliente')

    # ### end Alembic commands ###
